services:
  - type: web
    name: neet-platform
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: neet-platform-db
          property: connectionString
      - key: FLASK_ENV
        value: production

databases:
  - name: neet-platform-db
    plan: starter
